{% extends "layout.volt" %}
{% block content %}
<div class="page-heading"><div><div class="eyebrow"><span class="tiny-dot"></span> ОБЗОР ИНФРАСТРУКТУРЫ</div><h1>Ваши сайты. Одним взглядом<span>.</span></h1><p>Доступность, версии и репозитории — всё в одном месте.</p></div><a class="button primary" href="/sites/new"><svg><use href="/assets/icons.svg#plus"></use></svg>Добавить сайт</a></div>
{% if notice %}<div class="notice" role="status"><svg><use href="/assets/icons.svg#check"></use></svg>{{ notice }}</div>{% endif %}
<section class="stats" aria-label="Сводка">
    <div class="stat-card"><div class="stat-label">Всего сайтов<svg><use href="/assets/icons.svg#globe"></use></svg></div><div class="stat-value">{{ stats['total'] }}<span>в вашей панели</span></div></div>
    <div class="stat-card"><div class="stat-label">В сети<span class="status-dot green"></span></div><div class="stat-value">{{ stats['online'] }}<span>последняя проверка</span></div></div>
    <div class="stat-card"><div class="stat-label">Требуют внимания<svg class="amber"><use href="/assets/icons.svg#activity"></use></svg></div><div class="stat-value">{{ stats['attention'] }}<span>проверки и обновления</span></div></div>
    <div class="stat-card"><div class="stat-label">На паузе<svg><use href="/assets/icons.svg#pause"></use></svg></div><div class="stat-value">{{ stats['paused'] }}<span>проверки отключены</span></div></div>
</section>
<section class="sites-section" aria-label="Сайты">
    <div class="section-toolbar"><div class="filter-tabs" role="group" aria-label="Фильтр сайтов"><button class="filter-tab selected" data-filter="all" aria-pressed="true">Все сайты<span>{{ stats['total'] }}</span></button><button class="filter-tab" data-filter="attention" aria-pressed="false">Требуют внимания</button><button class="filter-tab" data-filter="paused" aria-pressed="false">На паузе</button></div><label class="search"><svg><use href="/assets/icons.svg#search"></use></svg><input type="search" id="site-search" placeholder="Найти сайт…" aria-label="Найти сайт"></label></div>
    <div class="site-grid">
    {% for site in sites %}
        <article class="site-card" data-site data-search="{{ site['name'] }} {{ site['host'] }} {{ site['repository'] }}" data-paused="{% if not site['enabled'] %}1{% else %}0{% endif %}" data-attention="{% if site['attention'] %}1{% else %}0{% endif %}">
            <div class="card-header"><div class="site-identity"><div class="site-monogram">{{ site['initial'] }}</div><div><h2><a href="{{ site['url'] }}" target="_blank" rel="noopener noreferrer">{{ site['name'] }}<svg><use href="/assets/icons.svg#external"></use></svg></a></h2><a class="site-host" href="{{ site['url'] }}" target="_blank" rel="noopener noreferrer">{{ site['host'] }}</a></div></div><span class="status-pill {{ site['tone'] }}"><span class="status-dot {{ site['tone'] }}"></span>{{ site['status'] }}</span></div>
            <div class="repo-line"><svg><use href="/assets/icons.svg#github"></use></svg><a href="https://github.com/{{ site['repository'] }}" target="_blank" rel="noopener noreferrer">{{ site['repository'] }}</a><span class="branch"><svg><use href="/assets/icons.svg#branch"></use></svg>{{ site['branch'] }}</span></div>
            <div class="version-panel"><div class="version-labels"><span>НА САЙТЕ</span><span>{% if site['comparison_mode'] == 'release' %}ПОСЛЕДНИЙ РЕЛИЗ{% else %}HEAD ВЕТКИ{% endif %}</span></div><div class="version-values"><code>{{ site['deployed_label'] }}</code><svg><use href="/assets/icons.svg#arrow"></use></svg><code>{{ site['latest_label'] }}</code></div><div class="comparison {{ site['comparison_tone'] }}"><svg><use href="/assets/icons.svg#{% if site['comparison_tone'] == 'green' %}check{% elseif site['comparison_tone'] == 'amber' %}activity{% else %}clock{% endif %}"></use></svg>{{ site['comparison'] }}</div></div>
            <div class="site-metrics"><a href="https://github.com/{{ site['repository'] }}/issues" target="_blank" rel="noopener noreferrer"><svg><use href="/assets/icons.svg#issue"></use></svg>Issues<strong>{% if site['open_issues'] is defined and site['open_issues'] !== null %}{{ site['open_issues'] }}{% else %}—{% endif %}</strong></a><a href="https://github.com/{{ site['repository'] }}/pulls" target="_blank" rel="noopener noreferrer"><svg><use href="/assets/icons.svg#pr"></use></svg>PR<strong>{% if site['open_prs'] !== null %}{{ site['open_prs'] }}{% else %}—{% endif %}</strong></a><span><svg><use href="/assets/icons.svg#activity"></use></svg><strong>{% if site['response_time_ms'] !== null %}{{ site['response_time_ms'] }}{% else %}—{% endif %}</strong>мс</span></div>
            {% if site['last_error'] %}<details class="check-error"><summary>Есть ошибки проверки</summary><p>{{ site['last_error'] }}</p></details>{% endif %}
            <div class="card-footer"><span><svg><use href="/assets/icons.svg#clock"></use></svg>{{ site['checked_label'] }}{% if site['stale'] %}<b class="stale-label"> · Устарело</b>{% endif %}</span><div class="card-actions"><form action="/sites/{{ site['id'] }}/check" method="post" data-check><input type="hidden" name="_csrf" value="{{ csrf }}"><button class="icon-button" title="Проверить сайт" aria-label="Проверить {{ site['name'] }}" {% if not site['enabled'] %}disabled{% endif %}><svg><use href="/assets/icons.svg#refresh"></use></svg></button></form><a class="icon-button" href="/sites/{{ site['id'] }}/edit" title="Настройки сайта" aria-label="Настройки {{ site['name'] }}"><svg><use href="/assets/icons.svg#settings"></use></svg></a></div></div>
        </article>
    {% endfor %}
    <a class="add-card" href="/sites/new"><span class="add-card-icon"><svg><use href="/assets/icons.svg#plus"></use></svg></span><strong>Ещё один сайт под контролем</strong><span>Добавьте сайт и его репозиторий</span><span class="add-card-link">Добавить сайт <svg><use href="/assets/icons.svg#arrow"></use></svg></span></a>
    </div>
    <p class="no-results" hidden>По вашему запросу ничего не найдено.</p>
    {% if stats['total'] == 0 %}<p class="first-site-hint">Начните с первого сайта. Укажите адрес, репозиторий и endpoints для проверки.</p>{% endif %}
    <div class="dashboard-note"><svg><use href="/assets/icons.svg#info"></use></svg><span>Данные обновляются по кнопке проверки. Время последней проверки указано на каждой карточке.</span></div>
</section>
{% endblock %}
