display_errors = Off
log_errors = On
expose_php = Off
post_max_size = 16K
upload_max_filesize = 16K
max_execution_time = 60
session.use_strict_mode = 1
session.cookie_httponly = 1
session.cookie_samesite = Strict
